import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";

import { Nav } from "./components/Nav";
import { Footer } from "./components/Footer";

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "mohammad taghinasab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
