import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";

import { Nav } from "./components/Nav";
import { Footer } from "./components/Footer";

import { Inter } from "next/font/google";
import { ResumeModal } from "./components/ResumeModal";
import { SiteProvider, SiteContext } from "./context/site-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "mohammad taghinasab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { theme } = React.useContext(SiteContext);

  return (
    <SiteProvider>
      <html lang="en">
        <body className={`${inter.className} ${theme}`} >
          <Nav />
          <ResumeModal />
          {children}
          <Footer />
        </body>
      </html>
    </SiteProvider>
  );
}
