import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";

import { SiteProvider } from "./context/site-context";
import { Provider } from "./components/Provider";

export const metadata = {
  title: "mohammad taghinasab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <SiteProvider>
      <html lang="en">
        <Provider>
          {children}
        </Provider>
      </html>
    </SiteProvider>
  );
}
